/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cdbank;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Casa
 */
public class TelaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaUsuario
     */
    public TelaUsuario() {
        initComponents();
        Utils u = new Utils();
        u.insertImage(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        depositarDinheiro = new javax.swing.JButton();
        sacarDinheiro = new javax.swing.JButton();
        trasferirDinheiro = new javax.swing.JButton();
        usuarioSaldo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela do Usuário");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DCBank");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Saldo disponível:");

        depositarDinheiro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        depositarDinheiro.setText("Depositar");
        depositarDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositarDinheiroActionPerformed(evt);
            }
        });

        sacarDinheiro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sacarDinheiro.setText("Sacar");
        sacarDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacarDinheiroActionPerformed(evt);
            }
        });

        trasferirDinheiro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        trasferirDinheiro.setText("Transferir");
        trasferirDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trasferirDinheiroActionPerformed(evt);
            }
        });

        usuarioSaldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usuarioSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(sacarDinheiro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(depositarDinheiro)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(trasferirDinheiro)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usuarioSaldo)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(usuarioSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositarDinheiro)
                    .addComponent(sacarDinheiro)
                    .addComponent(trasferirDinheiro))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sacarDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacarDinheiroActionPerformed
        // TODO add your handling code here:
        Saque formSaque = new Saque();
        formSaque.setVisible(true);
        
       
    }//GEN-LAST:event_sacarDinheiroActionPerformed

    private void depositarDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositarDinheiroActionPerformed
        // TODO add your handling code here:
        Deposito depositoForm = new Deposito();
        depositoForm.setVisible(true);
    }//GEN-LAST:event_depositarDinheiroActionPerformed

    private void trasferirDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trasferirDinheiroActionPerformed
        // TODO add your handling code here:
        Transferencia transForm = new Transferencia();
        transForm.setVisible(true);
         
    }//GEN-LAST:event_trasferirDinheiroActionPerformed

    private void usuarioSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioSaldoActionPerformed
            try {
            // TODO add your handling code here
            Connection conectando = ConexaoDb.conectar();
            
            String sql = "select saldo from usuario_cadastrado";
            
            PreparedStatement stmt = conectando.prepareStatement(sql);
            
            ResultSet resultado = stmt.executeQuery();
            
            
            stmt.close();
            conectando.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_usuarioSaldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton depositarDinheiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton sacarDinheiro;
    private javax.swing.JButton trasferirDinheiro;
    private javax.swing.JTextField usuarioSaldo;
    // End of variables declaration//GEN-END:variables

    void setPushPathFieldText(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
